# Generated by Django 4.1.7 on 2023-02-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Scrum', 'Scrum software development'), ('Kanban', 'Kanban software development'), ('Basic', 'Basic software development')], max_length=10, verbose_name='Type'),
        ),
    ]
