# Generated by Django 4.1.7 on 2023-02-27 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdf', '0002_alter_project_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255, verbose_name='Tittle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sdf.project')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_summary', models.CharField(max_length=100, verbose_name='Summary')),
                ('task_status', models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='New', max_length=20)),
                ('task_type', models.CharField(choices=[('task', 'Task'), ('story', 'Story'), ('bug', 'Bug'), ('feature', 'Feature')], default=None, max_length=50, null=True, verbose_name='Type')),
                ('task_url', models.URLField(blank=True, verbose_name='URL')),
                ('task_description', models.TextField(verbose_name='Description')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Update date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, related_name='tasks', to='sdf.file', verbose_name='Files')),
                ('task_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sdf.category', verbose_name='Category')),
            ],
        ),
    ]
