# Generated by Django 4.1.7 on 2023-02-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdf', '0003_category_file_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='project',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sdf.project'),
            preserve_default=False,
        ),
    ]
