# Generated by Django 4.1.7 on 2023-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdf', '0004_remove_category_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In Progress'), ('Done', 'Done')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Story', 'Story'), ('Bug', 'Bug'), ('Feature', 'Feature')], default=None, max_length=50, null=True, verbose_name='Type'),
        ),
    ]
