# Generated by Django 4.1.7 on 2023-03-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdf', '0005_alter_task_task_status_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('To', 'To'), ('In progress', 'In Progress'), ('Done', 'Done')], default='New', max_length=20),
        ),
    ]
