# Generated by Django 4.1.7 on 2023-03-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdf', '0006_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In Progress'), ('Done', 'Done')], default='New', max_length=20),
        ),
    ]
