# Generated by Django 4.1.7 on 2023-03-05 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdf', '0007_alter_task_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leading_task', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
            preserve_default=False,
        ),
    ]
