# Generated by Django 4.1.7 on 2023-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdf', '0008_task_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
