# Generated by Django 4.1.7 on 2023-03-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdf', '0011_task_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('URGENT', 'URGENT')], default=None, max_length=50, null=True, verbose_name='Priority'),
        ),
    ]
