# Generated by Django 4.1.7 on 2023-02-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_extenduser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='first_name',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='last_name',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='company',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='job_title',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
