# Generated by Django 4.1.7 on 2023-03-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_extenduser_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='extenduser',
            managers=[
            ],
        ),
    ]
