# Generated by Django 4.1.7 on 2023-03-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_extenduser_pofile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extenduser',
            old_name='pofile_photo',
            new_name='profile_photo',
        ),
    ]
