# Generated by Django 4.1.7 on 2023-03-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_extenduser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='city',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='country',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='linkedin_profile',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='phone_number',
            field=models.CharField(blank=True, default='Unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='company',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='job_title',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
