# Generated by Django 4.1.7 on 2023-03-14 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_extenduser_git_hub_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='git_hub_profile',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
